// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClN81sj1bjQQtE3gffX40gGcMhL4kGmzw',
    appId: '1:273633366599:web:2c6cd22ad95994a6f4d762',
    messagingSenderId: '273633366599',
    projectId: 'airigo-jobs',
    authDomain: 'airigo-jobs.firebaseapp.com',
    storageBucket: 'airigo-jobs.firebasestorage.app',
    measurementId: 'G-KTGJK1GKH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbU3xaTaB9hjBlNa3PR-WJlKpmbVzcXPE',
    appId: '1:273633366599:android:deb49befd838315df4d762',
    messagingSenderId: '273633366599',
    projectId: 'airigo-jobs',
    storageBucket: 'airigo-jobs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClN81sj1bjQQtE3gffX40gGcMhL4kGmzw',
    appId: '1:273633366599:web:4fd0eea263cd23d2f4d762',
    messagingSenderId: '273633366599',
    projectId: 'airigo-jobs',
    authDomain: 'airigo-jobs.firebaseapp.com',
    storageBucket: 'airigo-jobs.firebasestorage.app',
    measurementId: 'G-DXDL5BG8RX',
  );
}
